name: Auto reply on new issues
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add thanks comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for the request! I’ll review and reply with a scoped quote within **12–24 hours**.
            For urgent requests, email **your@email.com** or Telegram **@yourtelegram**.
      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs-triage
